server:
  servlet:
    contextPath: /test/v1
  port: 8080
  
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Mexico_City
    locale: es_MX    
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/escueladb
    username: owner
    password: password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Mexico_City
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  config:
    activate:
      on-profile:
        default